name: app_caffe_shop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Ui and router 
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  
  auto_size_text: ^3.0.0
  auto_route: ^8.2.0
  auto_route_generator: ^8.0.0
  flutter_screenutil: ^5.9.3
  very_good_analysis: ^6.0.0
  persistent_bottom_nav_bar_v2: ^5.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/src/assets/bottom_nav_bar_icons/
    - lib/src/assets/detail/
    - lib/src/assets/home/
    - lib/src/assets/icons/
    - lib/src/assets/image_on_design/
  